## MY ALIASES
alias hello="cowsay hello, motherfucker."
alias get="sudo pacman -S"
alias remove="sudo pacman -R"
alias update="sudo pacman -Sy"
alias upgrade="sudo pacman -Syu"
alias search="pacman -Ss"
alias sif="sudo ifconfig"
alias nf="neofetch"
alias ht="htop"
alias bt="btop"
alias cm="cmatrix -u 100"
alias thm="sudo openvpn ~/vpn/thm.ovpn&"
alias htbsp="sudo openvpn ~/vpn/htb_starting_point.ovpn&"
alias home="sudo openvpn ~/vpn/home.ovpn&"
alias p1="ping 1.1.1.1"
